{% set version = "0.7.5" %}
{% set name = "pynac" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://github.com/pynac/pynac/releases/download/pynac-{{ version }}/pynac-{{ version }}.tar.bz2
  sha256: b37f16282b6cb2cc8dde1d2b1835c1413fc9f0ab1bf32405dca1d4916836d549

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - libtool
    - pkg-config
    - python
    - gmp >=5.0.1,<7
    - mpfr 3.*
    - libflint 2.5.*
    - singular 4.1.0.p3

  run:
    - python
    - gmp >=5.0.1,<7
    - mpfr 3.*
    - libflint 2.5.*
    - singular 4.1.0.p3

test:
  commands:
    - test -f ${PREFIX}/include/pynac/ginac.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]

about:
  home: http://pynac.org/
  license: GPLv2+
  license_file: COPYING
  summary: Pynac -- symbolic computation with Python objects
  dev_url: https://github.com/pynac/pynac

extra:
  recipe-maintainers:
    - isuruf
